services:
  - type: web
    name: findfast-job-portal
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: FIREBASE_DATABASE_URL
        value: https://find-any-55a42-default-rtdb.firebaseio.com/
      - key: FLASK_SECRET_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
