"""Aliases used to identify equivalent application-form fields."""

# Keep these aliases broad enough for different job boards, but attach them to
# one standard profile key so the filler never has to guess the value source.
FIELD_MAPPINGS = {
    'first_name': ['first name', 'given name', 'forename', 'name'],
    'last_name': ['last name', 'surname', 'family name'],
    'full_name': ['full name', 'applicant name', 'candidate name'],
    'email': ['email', 'e-mail', 'email address'],
    'contact_number': ['cell', 'cellphone', 'mobile', 'telephone', 'phone', 'contact number'],
    'id_number': ['id number', 'identity number', 'national id', 'passport number'],
    'date_of_birth': ['date of birth', 'birth date', 'dob'],
    'gender': ['gender', 'sex'],
    'ethnicity': ['race', 'ethnicity', 'employment equity'],
    'nationality': ['nationality', 'citizenship'],
    'country': ['country', 'country of residence'],
    'province': ['province', 'state', 'region'],
    'city': ['city', 'town', 'suburb'],
    'postal_code': ['postal code', 'postcode', 'zip code'],
    'street_address': ['street address', 'residential address', 'home address'],
    'current_job_title': ['current job title', 'current position'],
    'current_company': ['current employer', 'current company'],
    'professional_summary': ['professional summary', 'profile summary', 'about you'],
    'linkedin_profile': ['linkedin', 'linkedin profile'],
    'github_profile': ['github', 'github profile'],
    'portfolio_website': ['portfolio', 'personal website', 'website'],
    'work_authorisation': ['eligible to work', 'work authorisation', 'work authorization', 'visa status'],
    'notice_period': ['notice period'],
    'preferred_job_location': ['preferred location', 'job location', 'work location'],
    'education_institution': ['institution', 'school', 'college', 'university'],
    'education_qualification': ['qualification', 'degree', 'education', 'highest qualification'],
    'education_field_of_study': ['field of study', 'major', 'specialization', 'specialisation'],
    'education_start_date': ['education start date', 'study start date', 'from date'],
    'education_end_date': ['education end date', 'study end date', 'to date'],
    'education_description': ['education description', 'course description'],
    'experience_company': ['employer', 'employer name', 'company', 'company name', 'organisation', 'organization'],
    'experience_position': ['job title', 'position', 'role', 'role title'],
    'experience_start_date': ['start date', 'from date', 'employment start'],
    'experience_end_date': ['end date', 'to date', 'employment end'],
    'experience_responsibilities': ['responsibilities', 'duties', 'key responsibilities'],
    'experience_achievements': ['achievements', 'accomplishments'],
    'experience_description': ['work description', 'job description', 'employment description'],
    'experience_employment_type': ['employment type', 'type of employment'],
    'middle_name': ['middle name', 'second name'],
    'preferred_name': ['preferred name', 'known as', 'nickname'],
    'country_of_residence': ['country of residence', 'residential country'],
    'alternative_email': ['alternative email', 'secondary email', 'other email'],
    'alternative_contact_number': ['alternative contact', 'secondary phone', 'other phone'],
    'willing_to_relocate': ['willing to relocate', 'relocate'],
    'willing_to_travel': ['willing to travel', 'travel'],
    'preferred_work_arrangement': ['work arrangement', 'work preference', 'remote or on-site'],
    'preferred_employment_type': ['preferred employment type', 'employment preference'],
    'current_employment_status': ['employment status', 'current employment status'],
    'professional_headline': ['professional headline', 'headline', 'tagline'],
    'years_of_experience': ['years of experience', 'experience in years', 'total experience'],
    'career_level': ['career level', 'experience level', 'seniority'],
    'desired_job_title': ['desired job title', 'target job title', 'position sought'],
    'desired_salary': ['desired salary', 'expected salary', 'salary expectation'],
    'currency': ['currency', 'salary currency'],
    'drivers_license': ['driver license', "driver's license", 'driving license'],
    'license_type': ['license type', 'driving license type'],
    'own_transport': ['own transport', 'own vehicle', 'reliable transport'],
    'visa_status': ['visa status', 'work visa'],
    'institution_type': ['institution type', 'school type'],
    'specialisation': ['specialisation', 'specialization', 'concentration'],
    'currently_studying': ['currently studying', 'still studying'],
    'education_country': ['education country', 'study country'],
    'education_province': ['education province', 'study province'],
    'education_city': ['education city', 'study city'],
    'grade': ['grade', 'average', 'gpa', 'result'],
    'experience_country': ['employment country', 'work country'],
    'experience_province': ['employment province', 'work province'],
    'experience_city': ['employment city', 'work city'],
    'currently_working_here': ['currently working here', 'current job', 'present'],
    'skill_name': ['skill', 'skill name', 'technology', 'technical skill'],
    'skill_category': ['skill category', 'area of skill'],
    'proficiency_level': ['proficiency', 'skill level', 'competency level'],
    'certification_name': ['certification', 'certificate', 'certification name'],
    'issuing_organisation': ['issuing organisation', 'issuing organization', 'issued by'],
    'issue_date': ['issue date', 'date issued', 'certification date'],
    'expiry_date': ['expiry date', 'expiration date', 'valid until'],
    'credential_id': ['credential id', 'certificate number', 'license number'],
    'credential_url': ['credential url', 'certificate url', 'verification url'],
    'does_not_expire': ['does not expire', 'no expiry', 'never expires'],
    'language': ['language', 'spoken language'],
    'speaking_proficiency': ['speaking proficiency', 'spoken proficiency'],
    'reading_proficiency': ['reading proficiency'],
    'writing_proficiency': ['writing proficiency'],
    'project_name': ['project name', 'project'],
    'project_description': ['project description'],
    'project_role': ['project role', 'role on project'],
    'project_start_date': ['project start date'],
    'project_end_date': ['project end date'],
    'technologies_used': ['technologies used', 'tools used', 'technology stack'],
    'project_url': ['project url', 'project link'],
    'github_url': ['github url', 'github link'],
    'membership_organisation': ['membership organisation', 'professional organisation'],
    'membership_type': ['membership type', 'member type'],
    'membership_number': ['membership number', 'member number'],
    'membership_start_date': ['membership start date'],
    'membership_end_date': ['membership end date'],
    'reference_full_name': ['reference name', 'referee name', 'reference full name'],
    'reference_job_title': ['reference job title', 'referee position'],
    'reference_company': ['reference company', 'referee company'],
    'reference_relationship': ['reference relationship', 'relationship to referee'],
    'reference_email': ['reference email', 'referee email'],
    'reference_contact_number': ['reference contact', 'referee phone'],
    'available_upon_request': ['available upon request', 'references available'],
    'document_name': ['document name', 'supporting document'],
    'document_type': ['document type', 'attachment type'],
    'document_url': ['document url', 'document link'],
    'file_name': ['file name', 'upload file', 'attachment'],
}
